{{- $root := . -}}
{{- range $ingress, $ingressValue := .Values.ingresses }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" $root }}
  labels:
    app.kubernetes.io/name: {{ include "chart.name" $root }}
    app.kubernetes.io/instance: {{ $ingress }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service }}
  {{- with $ingressValue.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ $ingressValue.className }}
  {{- if $ingressValue.tls }}
  tls:
    {{- range $ingressValue.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $ingressValue.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "chart.fullname" $root }}-{{ $ingress }}
                port:
                  number: {{ $ingressValue.port }}
          {{- end }}
    {{- end }}
{{- end }}