secret_env_variables:
    OPENAPI: ENC[AES256_GCM,data:3zr9tuSzp3F62MlV,iv:6DLLqAK/2c5LCBs3oPfKpH768f51G0HVZlUX4xOhxxU=,tag:fRy8R1tBdmwlWhpo3tPLig==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-23T08:01:41Z"
    mac: ENC[AES256_GCM,data:lVu+6pgaU+UBAjhWvaw1gQs5+pj4oZC+2I25E3DZ3RePCsaLY3fMneHjX5BP7rSneRrDwSUV7F0kNswE10Q1II0hRfHoXXxWX1f6i6fIcLy0FlkvW/tnhu3cSPMLI/u548xDUEL+0A/9xbXiVoDg5//i9e1JF+C7Fw/C/z1eCIY=,iv:Ckpqu94NAtj5PE6JjthcCLr21URX1+BPz2slNwEnvUc=,tag:Ojqd7M24pMUc/CedEz2amQ==,type:str]
    pgp:
        - created_at: "2024-12-21T15:18:44Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA+7ekPbCuJHsAQwAkIUv7ockd+ICw3Xei1yFIIJTwpCvn7Ra39DQd4X6mGMz
            xWj1e1Wca9XxQf6hgUDDPwwY7fGLWd6KTHQyxAR2fFqVyj/BRUmVubaYpP2rjhlx
            wlvWwkfr6NMmNctJ0MMFdsgl/hbwxtH8VccOyTBz7nObkW9KCnnw7CXUD/E8WGhb
            2oYKBegHc4z9VXiOqIXXhiP9EqlCkn5i9oJIyaeJxVq3ELibPmmBeQFqjIHg1bN2
            AcVURyc5+g9a/FkMJnncwD+Z9UwLIkeePYl1/YaUhs/IoIfWfL2ccgZBMQjzkOfK
            ekqvqoyH7Mgqx30AunGTS5RKjljn6rj1E5CD6sPvB9boUCHLcrxh4BzUIUDURbN3
            jL1VCZUWx40rLNRE7R6mcUe3D8IKhl1nVuHC7O/EzaoNqZT3HzDcSah6uy//Kf0+
            L1ZY+VQxxJNgKACLb1mUp82x9lKl8O/WZbswA8Nofj3/I06fz36CbcZf8Sk3zBNt
            m5/mz1skXi/dqwIXHfWR0l4Bn7RXDCwDM5qg14cc8MX4+7viU/EoMaFramFGwnur
            frvfmIjUAxZPGTROWp3qPoah/gB7hGKmVhY05SdI25b315vxfbmQoABShQwaABlK
            Vm+0dhYg3Vk17yD+lOmi
            =3ZiQ
            -----END PGP MESSAGE-----
          fp: D85C59ACB904856AF3D108A20DDE1A9CC421A97C
    unencrypted_suffix: _unencrypted
    version: 3.7.1
